# Generated by Django 5.2.17 on 2026-10-01 07:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalshop', '0005_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredvideo',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='inventoryproducts',
            options={'ordering': ['-date_created'], 'verbose_name': 'product'},
        ),
        migrations.AlterModelOptions(
            name='moreimages',
            options={'verbose_name': 'gallery image'},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='otherpettycosts',
            options={'verbose_name_plural': 'other petty costs'},
        ),
        migrations.AlterModelOptions(
            name='pettycosts',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'petty costs'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='otherpettycosts',
            name='employee',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=30, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='featuredvideo',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='home_image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='unit_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='unit_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moreimages',
            name='more_images',
            field=models.ImageField(upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='generalshop.order'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalshop.inventoryproducts'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='otherpettycosts',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='otherpettycosts',
            name='others',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='otherpettycosts',
            name='pettycosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_costs', to='generalshop.pettycosts'),
        ),
        migrations.AlterField(
            model_name='pettycosts',
            name='airtime_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='pettycosts',
            name='lunch_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='pettycosts',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='orderedproduct',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='one_line_per_product'),
        ),
    ]
